FROM node:20-alpine as base
# ENV NODE_ENV=production
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
WORKDIR /app
RUN apk add --no-cache libc6-compat
RUN corepack enable && pnpm add -g @angular/cli

COPY . .
RUN pnpm install --frozen-lockfile

EXPOSE 4200
CMD ["ng", "serve", "--hmr", "--host", "0.0.0.0"]
