# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  server:
    build:
      context: ./server
    ports:
      - 8080:8080
    depends_on:
      - db
    profiles:
      - prod

  client:
    build:
      context: ./client
    # environment:
    # - NODE_ENV=production
    ports:
      - 4000:4000
    # environment:
    #   - ASPNETCORE_URLS=https://+:443;http://+:80
    #   - ASPNETCORE_HTTPS_PORT=443
    depends_on:
      - server
    # links:
    #   - server
    # networks:
    #   - aspnetappnetwork
    profiles:
      - prod

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 15432:8080
    depends_on:
      - db
    profiles:
      - dev

  dev-server:
    build:
      context: ./server
      args:
        - configuration=Debug
    ports:
      - 18080:8080
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    profiles:
      - dev

  dev-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 4200:4200
    depends_on:
      - dev-server
    volumes:
      - ./client:/app
    profiles:
      - dev

volumes:
  pgdata:
