# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  server:
    build:
      context: ./server
    ports:
      - 8080:8080
    depends_on:
      - db

  client:
    build:
      context: ./client
    ports:
      - 3000:80
    # environment:
    #   - ASPNETCORE_URLS=https://+:443;http://+:80
    #   - ASPNETCORE_HTTPS_PORT=443
    depends_on:
      - server
    # links:
    #   - server
    # networks:
    #   - aspnetappnetwork

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  debug-server:
    build:
      context: ./server
      args:
        - configuration=Debug
    ports:
      - 8081:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    profiles:
      - debug

volumes:
  pgdata:
