# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  server:
    build:
      context: ./server
    depends_on:
      - db
      - fastapi
    profiles:
      - prod
    networks:
      - summarizer_network
    environment:
      - POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}
      - LLM_API_URL=${LLM_API_URL}
    # environment:
    #   - ASPNETCORE_URLS=https://+:443;http://+:80
    #   - ASPNETCORE_HTTPS_PORT=443

  client:
    build:
      context: ./client
      args:
        - BACKEND_URL=${BACKEND_URL}
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - summarizer_network
    profiles:
      - prod

  fastapi:
    build:
      context: ./fastapi
    restart: always
    networks:
      - summarizer_network
    profiles:
      - prod
    volumes:
      - fastapi_data:/app/.cache

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - summarizer_network

  migrations:
    build:
      context: ./server
      dockerfile: migration.Dockerfile
      args:
        - POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}
    depends_on:
      - db
    profiles:
      - prod
      - adminer
    networks:
      - summarizer_network
    command: ["dotnet", "ef", "database", "update"] # DON'T RUN THIS COMMAND IN PRODUCTION

  adminer:
    image: adminer
    restart: always
    ports:
      - 15432:8080
    depends_on:
      - db
    profiles:
      - adminer
    networks:
      - summarizer_network

volumes:
  pgdata:
  fastapi_data:

networks:
  summarizer_network:
    name: summarizer_network
    driver: bridge
