# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  server:
    build:
      context: ./server
    ports:
      - 8080:8080

  debug-server:
    build:
      context: ./server
      args:
        - configuration=Debug
    ports:
      - 8081:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    profiles:
      - debug
  # client service for Angular app
  client:
    build:
      context: ./client
    ports:
      - 3000:80
    # environment:
    #   - ASPNETCORE_URLS=https://+:443;http://+:80
    #   - ASPNETCORE_HTTPS_PORT=443
    depends_on:
      - server
    # links:
    #   - server
    # networks:
    #   - aspnetappnetwork
