# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  server:
    container_name: summarizer-server
    image: ghcr.io/$REPO/server:$GITHUB_SHA
    depends_on:
      - db
    networks:
      - summarizer_network
    environment:
      - POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}
      - LLM_API_URL="http://fastapi:8000"
    profiles:
      - prod
    # volumes:
    #   - migrations:/migrations

  client:
    container_name: summarizer-client
    image: ghcr.io/$REPO/client:$GITHUB_SHA
    restart: always
    ports:
      - 3000:3000 # TODO: Add HTTPS support
    environment:
      - BACKEND_URL="http://summarizer-server:8080"
    depends_on:
      - server
    profiles:
      - prod
    networks:
      - summarizer_network

  # fastapi:
  #   container_name: summarizer-fastapi
  #   image: ghcr.io/$REPO/fastapi:$GITHUB_SHA
  #   restart: always
  #   networks:
  #     - summarizer_network
  #   profiles:
  #     - prod
  #   volumes:
  #     - fastapi_data:/app/.cache

  migrations:
    container_name: summarizer-migrations
    build:
      context: ../server
      dockerfile: migration.Dockerfile
      args:
        - POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}
    depends_on:
      - db
    networks:
      - summarizer_network
    environment:
      - POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}
    volumes:
      - migrations:/migrations
    profiles:
      - migrations

  db:
    container_name: summarizer-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - migrations:/migrations
    networks:
      - summarizer_network

volumes:
  pgdata:
  migrations:
  fastapi_data:

networks:
  summarizer_network:
    name: summarizer_network
    driver: bridge
