name: Build and push fastapi image

on:
  push:
    branches: ["main"]
    paths: ["fastapi/**"]
  pull_request:
    branches: ["main"]
    paths: ["fastapi/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log in to GitHub container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/fastapi:${{ github.sha }}
            ghcr.io/${{ github.repository }}/fastapi:latest
          file: ./fastapi/Dockerfile
          context: ./fastapi
